language: csharp
dist: trusty
mono: none
dotnet: 2.1.401

install:
- dotnet restore ${TRAVIS_BUILD_DIR}/src/toggl-cli.sln

script:
- dotnet build --output ${TRAVIS_BUILD_DIR}/build/toggl-cli --configuration Release --runtime win-x86 --framework net471 ${TRAVIS_BUILD_DIR}/src/toggl-cli.sln