language: csharp
dist: trusty
mono: none
dotnet: 2.1.401

install:
- dotnet restore

script:
- dotnet build --output ..\..\build\toggl-cli --configuration Release --runtime win-x86 --framework net471 .\src\toggl-cli.sln