version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build_script:
- ps: cd $env:APPVEYOR_BUILD_FOLDER/deploy; .\deploy.ps1
artifacts:
- path: release/toggl-cli
  name: togglhelper
deploy:
- provider: GitHub
  tag: togglhelper-v$(APPVEYOR_BUILD_NUMBER)
  release: togglhelper-v$(APPVEYOR_BUILD_NUMBER)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: MhikBEWdDfumEdvLUnHnGzSpCTLSkhOcISRGAmRNz6Y9MymD6gEl4aO1SBrYPBe7
  artifact: togglhelper