version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build_script:
- ps: >-
    $root = $(Get-Location).Path
    $solution = "$($root)\src\toggl-cli.sln"
    $build = "$($root)\build\toggl-cli"
    $publish = "$($root)\release\toggl-cli"
    $configuration = "Release"
    $runtime = "win-x86"
    $framework = "net471"
    dotnet restore $solution
    dotnet clean $solution
    dotnet restore $solution
    dotnet build --output $build --configuration $configuration --runtime $runtime --framework $framework $solution
    dotnet publish --output $publish --configuration $configuration --runtime $runtime --framework $framework $solution
artifacts:
- path: release/toggl-cli
  name: togglhelper
deploy:
- provider: GitHub
  tag: togglhelper-v$(APPVEYOR_BUILD_NUMBER)
  release: togglhelper-v$(APPVEYOR_BUILD_NUMBER)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: MhikBEWdDfumEdvLUnHnGzSpCTLSkhOcISRGAmRNz6Y9MymD6gEl4aO1SBrYPBe7
  artifact: togglhelper