version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build_script:
- ps: >-
    dotnet restore $env:APPVEYOR_BUILD_FOLDER/src/toggl-cli.sln
    dotnet clean $env:APPVEYOR_BUILD_FOLDER/src/toggl-cli.sln
    dotnet restore $env:APPVEYOR_BUILD_FOLDER/src/toggl-cli.sln
    dotnet build --output $env:APPVEYOR_BUILD_FOLDER/build/toggl-cli --configuration Release --runtime win-x86 --framework net471 $env:APPVEYOR_BUILD_FOLDER/src/toggl-cli.sln
    dotnet publish --output $env:APPVEYOR_BUILD_FOLDER/release/toggl-cli --configuration Release --runtime win-x86 --framework net471 $env:APPVEYOR_BUILD_FOLDER/src/toggl-cli.sln
artifacts:
- path: release/toggl-cli
  name: togglhelper
deploy:
- provider: GitHub
  tag: togglhelper-v$(APPVEYOR_BUILD_NUMBER)
  release: togglhelper-v$(APPVEYOR_BUILD_NUMBER)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: MhikBEWdDfumEdvLUnHnGzSpCTLSkhOcISRGAmRNz6Y9MymD6gEl4aO1SBrYPBe7
  artifact: togglhelper