version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build_script:
- ps: >-
    $env:root = $(Get-Location).Path
    $env:solution = "$($env:root)\src\toggl-cli.sln"
    $env:build = "$($env:root)\build\toggl-cli"
    $env:publish = "$($env:root)\release\toggl-cli"
    $env:configuration = "Release"
    $env:runtime = "win-x86"
    $env:framework = "net471"
    dotnet restore $env:solution
    dotnet clean $env:solution
    dotnet restore $env:solution
    dotnet build --output $env:build --configuration $env:configuration --runtime $env:runtime --framework $env:framework $env:solution
    dotnet publish --output $env:publish --configuration $env:configuration --runtime $env:runtime --framework $env:framework $env:solution
artifacts:
- path: release/toggl-cli
  name: togglhelper
deploy:
- provider: GitHub
  tag: togglhelper-v$(APPVEYOR_BUILD_NUMBER)
  release: togglhelper-v$(APPVEYOR_BUILD_NUMBER)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: MhikBEWdDfumEdvLUnHnGzSpCTLSkhOcISRGAmRNz6Y9MymD6gEl4aO1SBrYPBe7
  artifact: togglhelper